### ISSUE TITLE
Subfolders crash the app

### ISSUE THREAD

**Issue by Quest84** [SeanOMik/eBookReaderSwitch#11]
Having subfolders inside books/ crashes the console

**Comment by SeanOMik** [comment]
I was actually able to fix my broken switch, I used folded paper to put a little bit of pressure on the "lego" connector on the motherboard. 

Since my switch it fixed, I could probably try to fix this. I wasn't able to get libtwili linked in my environment (Ubuntu WSL 2), however, it shouldn't matter that much.

**Comment by Quest84** [comment]
> I was actually able to fix my broken switch, I used folded paper to put a little bit of pressure on the "lego" connector on the motherboard.

Wow that's pretty cool man! 

> Since my switch it fixed, I could probably try to fix this. I wasn't able to get libtwili linked in my environment (Ubuntu WSL 2), however, it shouldn't matter that much.

Yeah, I couldn't make libtwili work on linux mint either. Maybe you could use nxlink to send prints to the console. I tried it but couldn't make it work, every time I send a large nsp through nxlink I get an I/O error. 

I've been trying to fix the scroll on the books menu but since I don't know how SDL works I can't do much, so I'm currently studying it

**Comment by ericzx505** [comment]
I know I am about 3 years late but I have made a fork that includes the ability to use folders. https://gitlab.com/DrEAMS99/eBookReaderSwitch

**Comment by Quest84** [comment]
> I know I am about 3 years late but I have made a fork that includes the ability to use folders. https://gitlab.com/DrEAMS99/eBookReaderSwitch

Nice, thanks for the contribution. If you don't mind, I'll merge the changes in my fork

**Comment by ericzx505** [comment]
absolulty and thank you for doing that, just be aware that I did change some of the button binds in the book reader mode.
